export const translations = {
  IT: {
    pricingTitle: "Piani di Accelerazione",
    pricingSubtitle: "Scegli il tuo livello di evoluzione digitale.",
    startTitle: "Essential",
    startPrice: "849\u20AC",
    startFeatures: [
      "Sito vetrina 5 pagine su misura",
      "SEO locale ottimizzata Torino/Piemonte",
      "Performance 100/100 mobile",
      "Design Cyber-Luxury (Glassmorphism)",
      "Hosting Europa 12 mesi incluso",
      "Consegna in 7 giorni lavorativi"
    ],
    evoTitle: "Professional",
    evoPrice: "1 599\u20AC",
    evoBadge: "Popolare",
    evoFeatures: [
      "Tutto il pacchetto Essential incluso",
      "Chatbot IA prenotazioni 24/7",
      "Sistema di booking automatico",
      "Sogni Lead Hub (Mini-CRM interno)",
      "Generazione di lead qualificati",
      "Dashboard analytics",
      "Formazione 1h utilizzo",
      "Consegna in 10 giorni lavorativi"
    ],
    infTitle: "Custom",
    infPrice: "2 999\u20AC+",
    infFeatures: [
      "Tutto il pacchetto Professional incluso",
      "Applicazione aziendale su misura",
      "App mobile nativa (iOS/Android)",
      "Sostituzione totale SaaS (HubSpot, ecc.)",
      "Integrazioni API di terze parti",
      "Database proprietario",
      "Formazione team completa",
      "Supporto prioritario 6 mesi"
    ],
    btnStart: "Inizia ora",
    serviziTitle1: "Architettura ",
    serviziTitle2: "Digitale.",
    serviziSubtitle: "Non creiamo solo siti web, costruiamo ecosistemi intelligenti progettati per convertire, automatizzare e dominare il mercato locale.",
    servizi1Title: "Siti Web AI & SEO",
    servizi1Desc: "Piattaforme web ultra-veloci, ottimizzate per i motori di ricerca e potenziate dall'intelligenza artificiale per massimizzare le conversioni.",
    servizi2Title: "Automazione Chatbot Intelligenti",
    servizi2Desc: "Assistenti virtuali attivi 24/7 che qualificano i lead, rispondono alle domande e prenotano appuntamenti mentre tu dormi.",
    servizi3Title: "Digitalizzazione Commercio Locale",
    servizi3Desc: "Portiamo la tua attivit\xE0 locale nel futuro con sistemi di prenotazione, e-commerce e strategie di visibilit\xE0 iper-locale.",
    dodoExtinction: "Estinzione",
    dodoEvolution: "Evoluzione",
    dodoMethod: "Il Metodo",
    dodoTitle1: "Dodo ",
    dodoTitle2: "Evolution.",
    dodoDesc1: "Il Dodo si \xE8 estinto perch\xE9 non ha saputo adattarsi al cambiamento. Nel mercato odierno, le imprese tradizionali rischiano la stessa fine.",
    dodoDesc2: "Con il nostro programma <strong>Dodo Evolution</strong>, prendiamo la tua attivit\xE0 storica e la dotiamo degli strumenti digitali e dell'intelligenza artificiale necessari per dominare la nuova era, preservando la tua identit\xE0 unica.",
    dodoCTA: "Salva il tuo business dall'estinzione",
    contactTitle: "Pronto per l'Evoluzione Digitale?",
    contactSubtitle: "Parla direttamente con un esperto di IA e Web Design a Torino.",
    contactWhatsApp: "Avvia Chat WhatsApp",
    contactFormName: "Nome",
    contactFormEmail: "Email",
    contactFormPhone: "Numero di Telefono",
    contactFormWebsite: "Sito Web Attuale (Opzionale)",
    contactFormBusiness: "Tipo di Business",
    contactFormMessage: "Messaggio",
    contactFormSubmit: "Invia Messaggio",
    contactInfoTitle: "Informazioni Aziendali",
    contactInfoCompany: "Ragione Sociale: Sogni Digitali",
    contactInfoLocation: "Sede: Torino, Italia",
    contactInfoVat: "P.IVA: IT13347550017",
    navServices: "Servizi",
    navMarketing: "Marketing",
    navPricing: "Prezzi",
    navContact: "Contatti",
    heroBadge: "Agenzia Web & AI \xB7 Torino",
    heroTitle1: "Trasformiamo i sogni in ",
    heroTitle2: "realt\xE0 digitale.",
    heroDesc: "Siti web ad alte prestazioni e soluzioni AI su misura per far crescere il tuo business in soli 7 giorni.",
    heroBtn1: "Inizia la tua evoluzione",
    heroBtn2: "Scopri i servizi",
    marketingTitle1: "Digital Marketing ",
    marketingTitle2: "& Growth.",
    marketingSubtitle: "Strategie basate sui dati e sull'Intelligenza Artificiale per dominare il tuo mercato locale e scalare i profitti.",
    mktService1Title: "Local SEO Power",
    mktService1Desc: "Scaliamo le classifiche di Google Maps a Torino per far arrivare i clienti direttamente nel tuo negozio.",
    mktService2Title: "AI Ads Strategy",
    mktService2Desc: "Campagne pubblicitarie intelligenti su Meta (Facebook/Instagram) e Google per massimizzare il ritorno sull'investimento (ROI).",
    mktService3Title: "Lead Generation Automata",
    mktService3Desc: "Sistemi integrati per catturare contatti qualificati e trasformarli in clienti fedeli tramite email marketing automatizzato.",
    mktService4Title: "Gestione Reputazione IA",
    mktService4Desc: "Analisi e risposta intelligente alle recensioni per mantenere un'immagine d'\xE9lite online.",
    ctaTitle1: "Pronto per il ",
    ctaTitle2: "prossimo livello?",
    ctaDesc: "Contattaci oggi. Ti risponderemo in meno di 2 ore con una strategia personalizzata.",
    footerDesc: "Agenzia di Web Design & Intelligenza Artificiale a Torino. Trasformiamo le imprese tradizionali in leader digitali.",
    footerExplore: "Esplora",
    footerPortfolio: "Portfolio",
    footerContactTitle: "Contatti",
    footerLocation: "Torino, Italia",
    footerAgencyName: "Sogni Digitali di D\xE9sir\xE9 Laval Oliver Polydor",
    footerVat: "Partita IVA: IT13347550017",
    footerCopyright: "\xA9 2026 Sogni Digitali. Tutti i diritti riservati.",
    footerUsefulLinks: "Link Utili",
    cookieBannerText: "Utilizziamo i cookie per migliorare la tua esperienza sul nostro sito. Puoi accettare tutti i cookie, rifiutarli o saperne di pi\xF9 leggendo la nostra Privacy Policy.",
    cookieAcceptAll: "Accetta tutti",
    cookieDecline: "Rifiuta",
    cookieLearnMore: "Scopri di pi\xF9",
    privacyPolicyTitle: "Informativa sulla Privacy",
    privacyPolicyContent: "La tua privacy \xE8 importante per noi. Questa informativa sulla privacy spiega quali dati personali raccogliamo, come li utilizziamo e come li proteggiamo. Raccogliamo dati tramite cookie e moduli di contatto per migliorare l'esperienza utente e fornire i nostri servizi. I tuoi dati non verranno venduti a terzi. Per qualsiasi richiesta relativa ai tuoi dati, puoi contattarci tramite i nostri canali ufficiali.",
    privacyPolicyClose: "Chiudi",
    seeAllPricing: "Scopri tutti i dettagli",
    terms: "Termini e Condizioni",
    pkgDetailsTitle: "Cosa includono i nostri pacchetti?",
    pkgDetailsSubtitle: "Un'analisi approfondita di ogni soluzione per aiutarti a scegliere l'evoluzione perfetta per il tuo business.",
    startDetailTitle: "Pacchetto START",
    startDetailDesc: "Ideale per le piccole imprese e i professionisti che vogliono stabilire una presenza online solida e professionale. Il pacchetto START ti fornisce un sito web vetrina moderno, veloce e ottimizzato per i motori di ricerca locali. Include l'hosting e il dominio per il primo anno, oltre all'integrazione diretta con WhatsApp per facilitare il contatto immediato con i tuoi clienti.",
    evoDetailTitle: "Pacchetto EVOLUTION",
    evoDetailDesc: "La nostra soluzione pi\xF9 popolare, progettata per le aziende che vogliono automatizzare l'acquisizione clienti. Oltre a tutte le funzionalit\xE0 del pacchetto START, EVOLUTION include un Chatbot basato sull'Intelligenza Artificiale in grado di rispondere alle domande frequenti 24/7, qualificare i contatti e raccogliere lead anche quando dormi. Ottimizziamo anche il tuo profilo Google Business per dominare le ricerche locali.",
    infDetailTitle: "Pacchetto INFINITY",
    infDetailDesc: "Per le aziende strutturate che necessitano di soluzioni su misura. INFINITY copre lo sviluppo di e-commerce avanzati, portali complessi o l'integrazione di API personalizzate basate sull'IA. Questo pacchetto include una consulenza strategica mensile per analizzare i dati e ottimizzare continuamente le performance del tuo ecosistema digitale.",
    subDetailsTitle: "Perch\xE9 scegliere un abbonamento?",
    subDetailsSubtitle: "Il mondo digitale evolve rapidamente. I nostri abbonamenti garantiscono che il tuo business rimanga sempre un passo avanti.",
    maintDetailTitle: "Mantenimento & Supporto",
    maintDetailDesc: "La tranquillit\xE0 di avere un team tecnico sempre a disposizione. Ci occupiamo degli aggiornamenti di sicurezza, dei backup settimanali per prevenire qualsiasi perdita di dati e delle modifiche minori al sito (fino a 2 ore al mese). Riceverai inoltre un report mensile dettagliato sulle performance del tuo sito web.",
    growthDetailTitle: "Crescita & Marketing",
    growthDetailDesc: "Il motore per scalare il tuo business. Gestiamo attivamente le tue campagne pubblicitarie su Meta (Facebook/Instagram) e Google Ads per massimizzare il ROI. Ottimizziamo continuamente la SEO, creiamo contenuti di valore (2 articoli al mese) e offriamo consulenza strategica bi-settimanale per adattare le tattiche alle risposte del mercato.",
    a11yTitle: "Accessibilit\xE0",
    a11yLargeText: "Testo pi\xF9 grande (Ipovedenti)",
    a11yContrast: "Contrasto elevato (Modalit\xE0 chiara)",
    a11yReduceMotion: "Ferma animazioni (Epilessia)",
    a11yDyslexiaFont: "Font per dislessia (Leggibilit\xE0)",
    contactWhatsAppSub: "Risposta in meno di 2 ore",
    backButton: "Torna Indietro",
    promoTitle: "Sblocca il 30% di Sconto!",
    promoDesc: "Lascia la tua email per ricevere il codice sconto esclusivo per il tuo primo progetto.",
    promoInput: "La tua migliore email",
    promoBtn: "Ottieni lo Sconto",
    promoSuccess: "Sconto inviato! Controlla la tua email.",
    pricingHeroBadge: "Sovranit\xE0 Digitale",
    pricingHeroTitle1: "Scegli il tuo ",
    pricingHeroTitle2: "livello di libert\xE0",
    pricingHeroDesc: "Senza abbonamenti tossici. Possiedi il tuo sistema. Ospitato in Europa. A vita.",
    pricingCtaEssential: "Scegli Essential",
    pricingCtaProfessional: "Scegli Professional",
    pricingCtaCustom: "Chiama il CEO",
    pricingDescEssential: "Presenza digitale sovrana",
    pricingDescProfessional: "La tua prima dipendente digitale",
    pricingDescCustom: "Il tuo OS aziendale proprietario",
    compTitle1: "Confronto ",
    compTitle2: "Dettagliato",
    compFeature: "FUNZIONALIT\xC0",
    oneShotTitle1: "Opzioni ",
    oneShotTitle2: "One-Shot",
    oneShotOption: "OPZIONE",
    careTitle1: "Sogni ",
    careTitle2: "Care",
    careTitle3: " (Manutenzione)",
    careDesc: "Perch\xE9 anche i sistemi sovrani hanno bisogno di manutenzione",
    trust1Value: "100%",
    trust1Desc: "Dati ospitati in Europa",
    trust2Value: "0\u20AC",
    trust2Desc: "Abbonamento SaaS tossico",
    trust3Value: "7-14gg",
    trust3Desc: "Tempi di consegna garantiti",
    finalCtaTitle: "Non sei sicuro della tua scelta?",
    finalCtaDesc: "Prenota una diagnosi gratuita di 20 minuti. Analizziamo il tuo stack attuale e ti diciamo esattamente di cosa hai bisogno.",
    finalCtaBtn: "Prenota la mia diagnosi gratuita",
    finalCtaSub: "Senza impegno. A Torino o in videochiamata.",
    faqTitle1: "Domande ",
    faqTitle2: "frequenti",
    viewComparison: "Vedi Confronto",
    hideComparison: "Nascondi Confronto",
    addMaintenance: "Aggiungi Sogni Care (Annuale)",
    oneShotSectionTitle: "Ottimizza la visibilit\xE0 della tua azienda",
    oneShotSectionDesc: "Servizi una tantum per dare una spinta immediata al tuo business.",
    careDescExtended: "La tranquillit\xE0 di avere un team tecnico sempre a disposizione. Ci occupiamo degli aggiornamenti di sicurezza, dei backup e delle modifiche minori per mantenere il tuo sistema sempre al top."
  },
  EN: {
    pricingTitle: "Acceleration Plans",
    pricingSubtitle: "Choose your level of digital evolution.",
    startTitle: "Essential",
    startPrice: "849\u20AC",
    startFeatures: [
      "Custom 5-page showcase website",
      "Local SEO optimized Turin/Piedmont",
      "Performance 100/100 mobile",
      "Cyber-Luxury Design (Glassmorphism)",
      "Europe Hosting 12 months included",
      "Delivery in 7 working days"
    ],
    evoTitle: "Professional",
    evoPrice: "1 599\u20AC",
    evoBadge: "Popular",
    evoFeatures: [
      "All Essential package included",
      "24/7 AI Booking Chatbot",
      "Automatic booking system",
      "Sogni Lead Hub (Internal Mini-CRM)",
      "Qualified lead generation",
      "Analytics dashboard",
      "1h usage training",
      "Delivery in 10 working days"
    ],
    infTitle: "Custom",
    infPrice: "2 999\u20AC+",
    infFeatures: [
      "All Professional package included",
      "Custom business application",
      "Native mobile app (iOS/Android)",
      "Total SaaS replacement (HubSpot, etc.)",
      "Third-party API integrations",
      "Proprietary database",
      "Full team training",
      "6 months priority support"
    ],
    btnStart: "Start now",
    serviziTitle1: "Digital ",
    serviziTitle2: "Architecture.",
    serviziSubtitle: "We don't just create websites, we build intelligent ecosystems designed to convert, automate, and dominate the local market.",
    servizi1Title: "AI & SEO Websites",
    servizi1Desc: "Ultra-fast web platforms, optimized for search engines and powered by artificial intelligence to maximize conversions.",
    servizi2Title: "Smart Chatbot Automation",
    servizi2Desc: "Virtual assistants active 24/7 that qualify leads, answer questions, and book appointments while you sleep.",
    servizi3Title: "Local Business Digitalization",
    servizi3Desc: "We bring your local business into the future with booking systems, e-commerce, and hyper-local visibility strategies.",
    dodoExtinction: "Extinction",
    dodoEvolution: "Evolution",
    dodoMethod: "The Method",
    dodoTitle1: "Dodo ",
    dodoTitle2: "Evolution.",
    dodoDesc1: "The Dodo went extinct because it couldn't adapt to change. In today's market, traditional businesses risk the same fate.",
    dodoDesc2: "With our <strong>Dodo Evolution</strong> program, we take your historic business and equip it with the digital tools and artificial intelligence needed to dominate the new era, while preserving your unique identity.",
    dodoCTA: "Save your business from extinction",
    contactTitle: "Ready for Digital Evolution?",
    contactSubtitle: "Speak directly with an AI and Web Design expert in Turin.",
    contactWhatsApp: "Start WhatsApp Chat",
    contactFormName: "Name",
    contactFormEmail: "Email",
    contactFormPhone: "Phone Number",
    contactFormWebsite: "Current Website (Optional)",
    contactFormBusiness: "Business Type",
    contactFormMessage: "Message",
    contactFormSubmit: "Send Message",
    contactInfoTitle: "Company Information",
    contactInfoCompany: "Company: Sogni Digitali",
    contactInfoLocation: "Location: Turin, Italy",
    contactInfoVat: "VAT: IT13347550017",
    navServices: "Services",
    navMarketing: "Marketing",
    navPricing: "Pricing",
    navContact: "Contact",
    heroBadge: "Web & AI Agency \xB7 Turin",
    heroTitle1: "We turn dreams into ",
    heroTitle2: "digital reality.",
    heroDesc: "High-performance websites and custom AI solutions to grow your business in just 7 days.",
    heroBtn1: "Start your evolution",
    heroBtn2: "Discover services",
    marketingTitle1: "Digital Marketing ",
    marketingTitle2: "& Growth.",
    marketingSubtitle: "Data-driven and AI-powered strategies to dominate your local market and scale your profits.",
    mktService1Title: "Local SEO Power",
    mktService1Desc: "We climb the Google Maps rankings in Turin to drive customers directly to your store.",
    mktService2Title: "AI Ads Strategy",
    mktService2Desc: "Intelligent advertising campaigns on Meta (Facebook/Instagram) and Google to maximize your Return on Investment (ROI).",
    mktService3Title: "Automated Lead Generation",
    mktService3Desc: "Integrated systems to capture qualified leads and turn them into loyal customers through automated email marketing.",
    mktService4Title: "AI Reputation Management",
    mktService4Desc: "Intelligent analysis and response to reviews to maintain an elite online image.",
    ctaTitle1: "Ready for the ",
    ctaTitle2: "next level?",
    ctaDesc: "Contact us today. We'll reply in less than 2 hours with a personalized strategy.",
    footerDesc: "Web Design & Artificial Intelligence Agency in Turin. We transform traditional businesses into digital leaders.",
    footerExplore: "Explore",
    footerPortfolio: "Portfolio",
    footerContactTitle: "Contact",
    footerLocation: "Turin, Italy",
    footerAgencyName: "Sogni Digitali by D\xE9sir\xE9 Laval Oliver Polydor",
    footerVat: "VAT: IT13347550017",
    footerCopyright: "\xA9 2026 Sogni Digitali. All rights reserved.",
    footerUsefulLinks: "Useful Links",
    cookieBannerText: "We use cookies to improve your experience on our site. You can accept all cookies, decline them, or learn more by reading our Privacy Policy.",
    cookieAcceptAll: "Accept all",
    cookieDecline: "Decline",
    cookieLearnMore: "Learn more",
    privacyPolicyTitle: "Privacy Policy",
    privacyPolicyContent: "Your privacy is important to us. This privacy policy explains what personal data we collect, how we use it, and how we protect it. We collect data through cookies and contact forms to improve the user experience and provide our services. Your data will not be sold to third parties. For any requests regarding your data, you can contact us through our official channels.",
    privacyPolicyClose: "Close",
    seeAllPricing: "See all details",
    terms: "Terms and Conditions",
    pkgDetailsTitle: "What's included in our packages?",
    pkgDetailsSubtitle: "An in-depth look at each solution to help you choose the perfect evolution for your business.",
    startDetailTitle: "START Package",
    startDetailDesc: "Ideal for small businesses and professionals who want to establish a solid and professional online presence. The START package provides you with a modern, fast showcase website optimized for local search engines. It includes hosting and domain for the first year, plus direct WhatsApp integration to facilitate immediate contact with your customers.",
    evoDetailTitle: "EVOLUTION Package",
    evoDetailDesc: "Our most popular solution, designed for companies that want to automate customer acquisition. In addition to all the features of the START package, EVOLUTION includes an AI-powered Chatbot capable of answering FAQs 24/7, qualifying contacts, and collecting leads even while you sleep. We also optimize your Google Business profile to dominate local searches.",
    infDetailTitle: "INFINITY Package",
    infDetailDesc: "For structured companies that need custom solutions. INFINITY covers the development of advanced e-commerce, complex portals, or the integration of custom AI-based APIs. This package includes monthly strategic consulting to analyze data and continuously optimize the performance of your digital ecosystem.",
    subDetailsTitle: "Why choose a subscription?",
    subDetailsSubtitle: "The digital world evolves rapidly. Our subscriptions ensure your business always stays one step ahead.",
    maintDetailTitle: "Maintenance & Support",
    maintDetailDesc: "The peace of mind of having a technical team always available. We take care of security updates, weekly backups to prevent any data loss, and minor site changes (up to 2 hours per month). You will also receive a detailed monthly report on your website's performance.",
    growthDetailTitle: "Growth & Marketing",
    growthDetailDesc: "The engine to scale your business. We actively manage your advertising campaigns on Meta (Facebook/Instagram) and Google Ads to maximize ROI. We continuously optimize SEO, create valuable content (2 articles per month), and offer bi-weekly strategic consulting to adapt tactics to market responses.",
    a11yTitle: "Accessibility",
    a11yLargeText: "Larger text (Visually impaired)",
    a11yContrast: "High contrast (Light mode)",
    a11yReduceMotion: "Stop animations (Epilepsy)",
    a11yDyslexiaFont: "Dyslexia font (Readability)",
    contactWhatsAppSub: "Response in under 2 hours",
    backButton: "Go Back",
    promoTitle: "Unlock 30% Off!",
    promoDesc: "Leave your email to receive an exclusive discount code for your first project.",
    promoInput: "Your best email",
    promoBtn: "Get the Discount",
    promoSuccess: "Discount sent! Check your email.",
    pricingHeroBadge: "Digital Sovereignty",
    pricingHeroTitle1: "Choose your ",
    pricingHeroTitle2: "level of freedom",
    pricingHeroDesc: "No toxic subscriptions. You own your system. Hosted in Europe. For life.",
    pricingCtaEssential: "Choose Essential",
    pricingCtaProfessional: "Choose Professional",
    pricingCtaCustom: "Call the CEO",
    pricingDescEssential: "Sovereign digital presence",
    pricingDescProfessional: "Your first digital employee",
    pricingDescCustom: "Your proprietary business OS",
    compTitle1: "Detailed ",
    compTitle2: "Comparison",
    compFeature: "FEATURE",
    oneShotTitle1: "One-Shot ",
    oneShotTitle2: "Options",
    oneShotOption: "OPTION",
    careTitle1: "Sogni ",
    careTitle2: "Care",
    careTitle3: " (Maintenance)",
    careDesc: "Because even sovereign systems need maintenance",
    trust1Value: "100%",
    trust1Desc: "Data hosted in Europe",
    trust2Value: "0\u20AC",
    trust2Desc: "Toxic SaaS subscription",
    trust3Value: "7-14d",
    trust3Desc: "Guaranteed delivery time",
    finalCtaTitle: "Not sure about your choice?",
    finalCtaDesc: "Book a free 20-minute diagnostic. We analyze your current stack and tell you exactly what you need.",
    finalCtaBtn: "Book my free diagnostic",
    finalCtaSub: "No commitment. In Turin or via video call.",
    faqTitle1: "Frequently Asked ",
    faqTitle2: "Questions",
    viewComparison: "View Comparison",
    hideComparison: "Hide Comparison",
    addMaintenance: "Add Sogni Care (Annual)",
    oneShotSectionTitle: "Optimize your business visibility",
    oneShotSectionDesc: "One-time services to give your business an immediate boost.",
    careDescExtended: "The peace of mind of having a technical team always available. We take care of security updates, backups, and minor changes to keep your system at its best."
  },
  FR: {
    pricingTitle: "Plans d'Acc\xE9l\xE9ration",
    pricingSubtitle: "Choisissez votre niveau d'\xE9volution num\xE9rique.",
    startTitle: "Essential",
    startPrice: "849\u20AC",
    startFeatures: [
      "Site vitrine 5 pages sur-mesure",
      "SEO local optimis\xE9 Turin/Pi\xE9mont",
      "Performance 100/100 mobile",
      "Design Cyber-Luxury (Glassmorphism)",
      "H\xE9bergement Europe 12 mois inclus",
      "Livraison en 7 jours ouvr\xE9s"
    ],
    evoTitle: "Professional",
    evoPrice: "1 599\u20AC",
    evoBadge: "Populaire",
    evoFeatures: [
      "Tout le pack Essential inclus",
      "Chatbot IA r\xE9servations 24/7",
      "Syst\xE8me de booking automatique",
      "Sogni Lead Hub (Mini-CRM interne)",
      "G\xE9n\xE9ration de leads qualifi\xE9s",
      "Tableau de bord analytics",
      "Formation 1h utilisation",
      "Livraison en 10 jours ouvr\xE9s"
    ],
    infTitle: "Custom",
    infPrice: "2 999\u20AC+",
    infFeatures: [
      "Tout le pack Professional inclus",
      "Application m\xE9tier sur-mesure",
      "App mobile native (iOS/Android)",
      "Remplacement total SaaS (HubSpot, etc.)",
      "Int\xE9grations API tierces",
      "Base de donn\xE9es propri\xE9taire",
      "Formation \xE9quipe compl\xE8te",
      "Support prioritaire 6 mois"
    ],
    btnStart: "Commencer",
    serviziTitle1: "Architecture ",
    serviziTitle2: "Num\xE9rique.",
    serviziSubtitle: "Nous ne cr\xE9ons pas seulement des sites web, nous construisons des \xE9cosyst\xE8mes intelligents con\xE7us pour convertir, automatiser et dominer le march\xE9 local.",
    servizi1Title: "Sites Web IA & SEO",
    servizi1Desc: "Plateformes web ultra-rapides, optimis\xE9es pour les moteurs de recherche et propuls\xE9es par l'intelligence artificielle pour maximiser les conversions.",
    servizi2Title: "Automatisation Chatbot Intelligents",
    servizi2Desc: "Assistants virtuels actifs 24/7 qui qualifient les leads, r\xE9pondent aux questions et prennent des rendez-vous pendant que vous dormez.",
    servizi3Title: "Digitalisation du Commerce Local",
    servizi3Desc: "Nous propulsons votre entreprise locale dans l'avenir avec des syst\xE8mes de r\xE9servation, de l'e-commerce et des strat\xE9gies de visibilit\xE9 hyper-locale.",
    dodoExtinction: "Extinction",
    dodoEvolution: "\xC9volution",
    dodoMethod: "La M\xE9thode",
    dodoTitle1: "Dodo ",
    dodoTitle2: "\xC9volution.",
    dodoDesc1: "Le Dodo a disparu parce qu'il n'a pas su s'adapter au changement. Sur le march\xE9 actuel, les entreprises traditionnelles risquent le m\xEAme sort.",
    dodoDesc2: "Avec notre programme <strong>Dodo \xC9volution</strong>, nous prenons votre activit\xE9 historique et la dotons des outils num\xE9riques et de l'intelligence artificielle n\xE9cessaires pour dominer la nouvelle \xE8re, tout en pr\xE9servant votre identit\xE9 unique.",
    dodoCTA: "Sauvez votre entreprise de l'extinction",
    contactTitle: "Pr\xEAt pour l'\xC9volution Num\xE9rique ?",
    contactSubtitle: "Parlez directement avec un expert en IA et Web Design \xE0 Turin.",
    contactWhatsApp: "D\xE9marrer le chat WhatsApp",
    contactFormName: "Nom",
    contactFormEmail: "Email",
    contactFormPhone: "Num\xE9ro de T\xE9l\xE9phone",
    contactFormWebsite: "Site Web Actuel (Optionnel)",
    contactFormBusiness: "Type d'Entreprise",
    contactFormMessage: "Message",
    contactFormSubmit: "Envoyer le message",
    contactInfoTitle: "Informations sur l'Entreprise",
    contactInfoCompany: "Soci\xE9t\xE9 : Sogni Digitali",
    contactInfoLocation: "Lieu : Turin, Italie",
    contactInfoVat: "TVA : IT13347550017",
    navServices: "Services",
    navMarketing: "Marketing",
    navPricing: "Tarifs",
    navContact: "Contact",
    heroBadge: "Agence Web & IA \xB7 Turin",
    heroTitle1: "Nous transformons les r\xEAves en ",
    heroTitle2: "r\xE9alit\xE9 num\xE9rique.",
    heroDesc: "Des sites web ultra-performants et des solutions IA sur mesure pour d\xE9velopper votre entreprise en seulement 7 jours.",
    heroBtn1: "Commencez votre \xE9volution",
    heroBtn2: "D\xE9couvrir les services",
    marketingTitle1: "Marketing Digital ",
    marketingTitle2: "& Croissance.",
    marketingSubtitle: "Des strat\xE9gies bas\xE9es sur les donn\xE9es et l'IA pour dominer votre march\xE9 local et faire \xE9voluer vos profits.",
    mktService1Title: "Puissance SEO Local",
    mktService1Desc: "Nous grimpons dans les classements Google Maps \xE0 Turin pour attirer les clients directement dans votre boutique.",
    mktService2Title: "Strat\xE9gie Publicitaire IA",
    mktService2Desc: "Campagnes publicitaires intelligentes sur Meta (Facebook/Instagram) et Google pour maximiser le retour sur investissement (ROI).",
    mktService3Title: "G\xE9n\xE9ration de Leads Automatis\xE9e",
    mktService3Desc: "Syst\xE8mes int\xE9gr\xE9s pour capturer des contacts qualifi\xE9s et les transformer en clients fid\xE8les via un marketing par e-mail automatis\xE9.",
    mktService4Title: "Gestion de R\xE9putation IA",
    mktService4Desc: "Analyse et r\xE9ponse intelligentes aux avis pour maintenir une image d'\xE9lite en ligne.",
    ctaTitle1: "Pr\xEAt pour le ",
    ctaTitle2: "niveau sup\xE9rieur ?",
    ctaDesc: "Contactez-nous aujourd'hui. Nous vous r\xE9pondrons en moins de 2 heures avec une strat\xE9gie personnalis\xE9e.",
    footerDesc: "Agence de Web Design & Intelligence Artificielle \xE0 Turin. Nous transformons les entreprises traditionnelles en leaders num\xE9riques.",
    footerExplore: "Explorer",
    footerPortfolio: "Portfolio",
    footerContactTitle: "Contact",
    footerLocation: "Turin, Italie",
    footerAgencyName: "Sogni Digitali par D\xE9sir\xE9 Laval Oliver Polydor",
    footerVat: "TVA : IT13347550017",
    footerCopyright: "\xA9 2026 Sogni Digitali. Tous droits r\xE9serv\xE9s.",
    footerUsefulLinks: "Liens Utiles",
    cookieBannerText: "Nous utilisons des cookies pour am\xE9liorer votre exp\xE9rience sur notre site. Vous pouvez accepter tous les cookies, les refuser ou en savoir plus en lisant notre Politique de confidentialit\xE9.",
    cookieAcceptAll: "Tout accepter",
    cookieDecline: "Refuser",
    cookieLearnMore: "En savoir plus",
    privacyPolicyTitle: "Politique de confidentialit\xE9",
    privacyPolicyContent: "Votre confidentialit\xE9 est importante pour nous. Cette politique de confidentialit\xE9 explique quelles donn\xE9es personnelles nous collectons, comment nous les utilisons et comment nous les prot\xE9geons. Nous collectons des donn\xE9es via des cookies et des formulaires de contact pour am\xE9liorer l'exp\xE9rience utilisateur et fournir nos services. Vos donn\xE9es ne seront pas vendues \xE0 des tiers. Pour toute demande concernant vos donn\xE9es, vous pouvez nous contacter via nos canaux officiels.",
    privacyPolicyClose: "Fermer",
    seeAllPricing: "Voir tous les d\xE9tails",
    terms: "Termes et Conditions",
    pkgDetailsTitle: "Que comprennent nos forfaits ?",
    pkgDetailsSubtitle: "Un regard approfondi sur chaque solution pour vous aider \xE0 choisir l'\xE9volution parfaite pour votre entreprise.",
    startDetailTitle: "Forfait START",
    startDetailDesc: "Id\xE9al pour les petites entreprises et les professionnels qui souhaitent \xE9tablir une pr\xE9sence en ligne solide et professionnelle. Le forfait START vous offre un site vitrine moderne, rapide et optimis\xE9 pour les moteurs de recherche locaux. Il inclut l'h\xE9bergement et le domaine pour la premi\xE8re ann\xE9e, ainsi qu'une int\xE9gration WhatsApp directe pour faciliter le contact imm\xE9diat avec vos clients.",
    evoDetailTitle: "Forfait EVOLUTION",
    evoDetailDesc: "Notre solution la plus populaire, con\xE7ue pour les entreprises qui souhaitent automatiser l'acquisition de clients. En plus de toutes les fonctionnalit\xE9s du forfait START, EVOLUTION inclut un Chatbot aliment\xE9 par l'IA capable de r\xE9pondre aux FAQ 24/7, de qualifier les contacts et de collecter des leads m\xEAme pendant votre sommeil. Nous optimisons \xE9galement votre profil Google Business pour dominer les recherches locales.",
    infDetailTitle: "Forfait INFINITY",
    infDetailDesc: "Pour les entreprises structur\xE9es qui ont besoin de solutions sur mesure. INFINITY couvre le d\xE9veloppement de l'e-commerce avanc\xE9, de portails complexes ou l'int\xE9gration d'API personnalis\xE9es bas\xE9es sur l'IA. Ce forfait comprend des conseils strat\xE9giques mensuels pour analyser les donn\xE9es et optimiser en permanence les performances de votre \xE9cosyst\xE8me num\xE9rique.",
    subDetailsTitle: "Pourquoi choisir un abonnement ?",
    subDetailsSubtitle: "Le monde num\xE9rique \xE9volue rapidement. Nos abonnements garantissent que votre entreprise garde toujours une longueur d'avance.",
    maintDetailTitle: "Maintenance & Support",
    maintDetailDesc: "La tranquillit\xE9 d'esprit d'avoir une \xE9quipe technique toujours disponible. Nous nous occupons des mises \xE0 jour de s\xE9curit\xE9, des sauvegardes hebdomadaires pour \xE9viter toute perte de donn\xE9es et des modifications mineures du site (jusqu'\xE0 2 heures par mois). Vous recevrez \xE9galement un rapport mensuel d\xE9taill\xE9 sur les performances de votre site Web.",
    growthDetailTitle: "Croissance & Marketing",
    growthDetailDesc: "Le moteur pour faire \xE9voluer votre entreprise. Nous g\xE9rons activement vos campagnes publicitaires sur Meta (Facebook/Instagram) et Google Ads pour maximiser le ROI. Nous optimisons continuellement le SEO, cr\xE9ons du contenu de valeur (2 articles par mois) et proposons des conseils strat\xE9giques bihebdomadaires pour adapter les tactiques aux r\xE9ponses du march\xE9.",
    a11yTitle: "Accessibilit\xE9",
    a11yLargeText: "Texte plus grand (Malvoyants)",
    a11yContrast: "Contraste \xE9lev\xE9 (Mode clair)",
    a11yReduceMotion: "Arr\xEAter les animations (\xC9pilepsie)",
    a11yDyslexiaFont: "Police Dyslexie (Lisibilit\xE9)",
    contactWhatsAppSub: "R\xE9ponse en moins de 2 heures",
    backButton: "Retour",
    promoTitle: "D\xE9bloquez 30% de R\xE9duction !",
    promoDesc: "Laissez votre e-mail pour recevoir un code de r\xE9duction exclusif pour votre premier projet.",
    promoInput: "Votre meilleur e-mail",
    promoBtn: "Obtenir la R\xE9duction",
    promoSuccess: "R\xE9duction envoy\xE9e ! V\xE9rifiez vos e-mails.",
    pricingHeroBadge: "Souverainet\xE9 Digitale",
    pricingHeroTitle1: "Choisissez votre ",
    pricingHeroTitle2: "niveau de libert\xE9",
    pricingHeroDesc: "Sans abonnement toxique. Vous poss\xE9dez votre syst\xE8me. H\xE9berg\xE9 en Europe. \xC0 vie.",
    pricingCtaEssential: "Choisir Essential",
    pricingCtaProfessional: "Choisir Professional",
    pricingCtaCustom: "Appeler le CEO",
    pricingDescEssential: "Pr\xE9sence digitale souveraine",
    pricingDescProfessional: "Votre premi\xE8re employ\xE9e digitale",
    pricingDescCustom: "Votre OS m\xE9tier propri\xE9taire",
    compTitle1: "Comparaison ",
    compTitle2: "D\xE9taill\xE9e",
    compFeature: "FONCTIONNALIT\xC9",
    oneShotTitle1: "Options ",
    oneShotTitle2: "One-Shot",
    oneShotOption: "OPTION",
    careTitle1: "Sogni ",
    careTitle2: "Care",
    careTitle3: " (Maintenance)",
    careDesc: "Parce que m\xEAme les syst\xE8mes souverains ont besoin d'entretien",
    trust1Value: "100%",
    trust1Desc: "Donn\xE9es h\xE9berg\xE9es en Europe",
    trust2Value: "0\u20AC",
    trust2Desc: "Abonnement SaaS toxique",
    trust3Value: "7-14j",
    trust3Desc: "D\xE9lai de livraison garanti",
    finalCtaTitle: "Pas s\xFBr de votre choix ?",
    finalCtaDesc: "R\xE9servez un diagnostic gratuit de 20 minutes. On analyse votre stack actuelle et on vous dit exactement ce dont vous avez besoin.",
    finalCtaBtn: "R\xE9server mon diagnostic gratuit",
    finalCtaSub: "Sans engagement. \xC0 Turin ou en visio.",
    faqTitle1: "Questions ",
    faqTitle2: "fr\xE9quentes",
    viewComparison: "Voir la Comparaison",
    hideComparison: "Masquer la Comparaison",
    addMaintenance: "Ajouter Sogni Care (Annuel)",
    oneShotSectionTitle: "Optimisez la visibilit\xE9 de votre entreprise",
    oneShotSectionDesc: "Des services ponctuels pour donner un coup de pouce imm\xE9diat \xE0 votre entreprise.",
    careDescExtended: "La tranquillit\xE9 d'esprit d'avoir une \xE9quipe technique toujours disponible. Nous nous occupons des mises \xE0 jour de s\xE9curit\xE9, des sauvegardes et des modifications mineures pour maintenir votre syst\xE8me au top."
  }
};
