import fs from 'fs';

let content = fs.readFileSync('src/lib/translations.ts', 'utf8');

const arStartIdx = content.indexOf('  AR: {');
const frStartIdx = content.indexOf('  FR: {');

if (arStartIdx !== -1 && frStartIdx !== -1) {
  const arabicTranslations = `  AR: {
    pricingTitle: "خطط التسريع",
    pricingSubtitle: "اختر مستوى تطورك الرقمي.",
    startTitle: "الأساسي",
    startPrice: "849€",
    startFeatures: [
      "موقع ويب مخصص بـ 5 صفحات",
      "تحسين محركات البحث المحلية للسوق",
      "أداء 100/100 على الهواتف",
      "تصميم حديث وفاخر",
      "استضافة أوروبية لمدة 12 شهرًا متضمنة",
      "تسليم في 7 أيام عمل"
    ],
    evoTitle: "الاحترافي",
    evoPrice: "1 599€",
    evoBadge: "شائع",
    evoFeatures: [
      "يتضمن جميع ميزات الباقة الأساسية",
      "تطبيق دردشة آلي يعمل بالذكاء الاصطناعي 24/7",
      "نظام حجز آلي",
      "نظام إدارة علاقات العملاء المبسط (Sogni Lead Hub)",
      "توليد عملاء محتملين مؤهلين",
      "لوحة تحكم تحليلية",
      "ساعة تدريب واحدة على الاستخدام",
      "تسليم في 10 أيام عمل"
    ],
    infTitle: "مخصص",
    infPrice: "2 999€+",
    infFeatures: [
      "يتضمن جميع ميزات الباقة الاحترافية",
      "تطبيق أعمال مخصص",
      "تطبيق للهواتف (iOS/Android)",
      "استبدال كامل للبرمجيات (HubSpot وغيرها)",
      "تكامل مع واجهات برمجة التطبيقات للأطراف الثالثة",
      "قاعدة بيانات خاصة",
      "تدريب كامل لفريق العمل",
      "دعم ذو أولوية لمدة 6 أشهر"
    ],
    btnStart: "ابدأ الآن",
    serviziTitle1: "البنية ",
    serviziTitle2: "الرقمية.",
    serviziSubtitle: "نحن لا ننشئ مواقع ويب فحسب، بل نبني أنظمة بيئية ذكية مصممة للتحويل والأتمتة والسيطرة على السوق المحلي.",
    servizi1Title: "مواقع ويب مدعومة بالذكاء الاصطناعي وتحسين محركات البحث",
    servizi1Desc: "منصات ويب فائقة السرعة، محسّنة لمحركات البحث ومُدعمة بالذكاء الاصطناعي لزيادة التحويلات.",
    servizi2Title: "أتمتة ذكية عبر روبوتات الدردشة",
    servizi2Desc: "مساعدون افتراضيون نشطون على مدار الساعة لتقييم العملاء والإجابة على الأسئلة وحجز المواعيد.",
    servizi3Title: "رقمنة الشركات المحلية",
    servizi3Desc: "نأخذ شركتك المحلية إلى المستقبل باستخدام أنظمة الحجز والتجارة الإلكترونية واستراتيجيات الظهور المحلي.",
    dodoExtinction: "انقراض",
    dodoEvolution: "تطور",
    dodoMethod: "المنهجية",
    dodoTitle1: "تطور ",
    dodoTitle2: "دودو.",
    dodoDesc1: "انقرض طائر الدودو لأنه لم يستطع التكيف مع التغيير. وفي سوق اليوم، تواجه الشركات التقليدية نفس المصير.",
    dodoDesc2: "من خلال برنامج <strong>تطور دودو</strong>، نأخذ شركتك التاريخية ونزودها بالأدوات الرقمية والذكاء الاصطناعي اللازم للسيطرة، مع الحفاظ على هويتك الفريدة.",
    dodoCTA: "أنقذ شركتك من الانقراض",
    contactTitle: "هل أنت مستعد للتطور الرقمي؟",
    contactSubtitle: "تحدث مباشرة مع خبير في الذكاء الاصطناعي وتصميم الويب في تورينو.",
    contactWhatsApp: "ابدأ الدردشة عبر واتساب",
    contactFormName: "الاسم",
    contactFormEmail: "البريد الإلكتروني",
    contactFormPhone: "رقم الهاتف",
    contactFormWebsite: "موقع الويب الحالي (اختياري)",
    contactFormBusiness: "نوع النشاط التجاري",
    contactFormMessage: "الرسالة",
    contactFormSubmit: "إرسال الرسالة",
    contactInfoTitle: "معلومات الشركة",
    contactInfoCompany: "الشركة: Sogni Digitali",
    contactInfoLocation: "الموقع: تورينو، إيطاليا",
    contactInfoVat: "الرقم الضريبي: IT13347550017",
    navServices: "الخدمات",
    navPackages: "باقاتنا",
    navMarketing: "التسويق",
    navPricing: "الأسعار",
    navContact: "اتصل بنا",
    heroBadge: "وكالة ويب وذكاء اصطناعي · تورينو",
    heroTitle1: "نُحوّل الأحلام إلى ",
    heroTitle2: "واقع رقمي.",
    heroDesc: "مواقع ويب عالية الأداء وحلول ذكاء اصطناعي مخصصة لتنمية أعمالك في 7 أيام فقط.",
    heroBtn1: "ابدأ تطورك",
    heroBtn2: "اكتشف الخدمات",
    marketingTitle1: "التسويق الرقمي ",
    marketingTitle2: "والنمو.",
    marketingSubtitle: "استراتيجيات مدعومة بالبيانات والذكاء الاصطناعي للسيطرة على سوقك المحلي وزيادة أرباحك.",
    mktService1Title: "قوة تحسين محركات البحث المحلية",
    mktService1Desc: "نتسلق تصنيفات خرائط جوجل لجلب العملاء مباشرة إلى متجرك.",
    mktService2Title: "استراتيجية الإعلانات المدعومة بالذكاء الاصطناعي",
    mktService2Desc: "حملات إعلانية ذكية لزيادة العائد على الاستثمار.",
    mktService3Title: "توليد عملاء محتملين آليًا",
    mktService3Desc: "أنظمة متكاملة لجذب عملاء مؤهلين وتحويلهم إلى عملاء مخلصين من خلال التسويق الآلي عبر البريد الإلكتروني.",
    mktService4Title: "إدارة السمعة بالذكاء الاصطناعي",
    mktService4Desc: "تحليل ذكي والرد على المراجعات للحفاظ على صورة إلكترونية متميزة.",
    ctaTitle1: "مستعد للمستوى ",
    ctaTitle2: "التالي؟",
    ctaDesc: "اتصل بنا اليوم. سنرد في أقل من ساعتين باستراتيجية مخصصة.",
    footerDesc: "وكالة تصميم ويب وذكاء اصطناعي في تورينو. نُحوّل الشركات التقليدية إلى قادة رقميين.",
    footerExplore: "استكشاف",
    footerPortfolio: "حافظة الأعمال",
    footerContactTitle: "اتصل بنا",
    footerLocation: "تورينو، إيطاليا",
    footerAgencyName: "Sogni Digitali من Désiré Laval Oliver Polydor",
    footerVat: "الرقم الضريبي: IT13347550017",
    footerCopyright: "© 2026 Sogni Digitali. جميع الحقوق محفوظة.",
    footerUsefulLinks: "روابط مفيدة",
    cookieBannerText: "نستخدم ملفات تعريف الارتباط لتحسين تجربتك على موقعنا. يمكنك قبول جميع ملفات تعريف الارتباط أو رفضها أو معرفة المزيد عن طريق قراءة سياسة الخصوصية الخاصة بنا.",
    cookieAcceptAll: "قبول الكل",
    cookieDecline: "رفض",
    cookieLearnMore: "معرفة المزيد",
    privacyPolicyTitle: "سياسة الخصوصية",
    privacyPolicyContent: "خصوصيتك تهمنا. تشرح سياسة الخصوصية هذه البيانات الشخصية التي نجمعها، وكيف نستخدمها، وكيف نحميها. نحن نجمع البيانات من خلال ملفات تعريف الارتباط ونماذج الاتصال لتحسين تجربة المستخدم وتقديم خدماتنا. لن يتم بيع بياناتك لأطراف ثالثة. لأي طلبات تتعلق ببياناتك، يمكنك الاتصال بنا من خلال قنواتنا الرسمية.",
    privacyPolicyClose: "إغلاق",
    seeAllPricing: "رؤية كافة التفاصيل",
    terms: "الشروط والأحكام",
    pkgDetailsTitle: "ماذا تتضمن باقاتنا؟",
    pkgDetailsSubtitle: "نظرة متعمقة على كل حل لمساعدتك في اختيار التطور المثالي لعملك.",
    startDetailTitle: "الباقة الأساسية",
    startDetailDesc: "مثالية للشركات الصغيرة والمهنيين الذين يرغبون في تأسيس حضور إلكتروني قوي واحترافي. توفر لك هذه الباقة موقع ويب حديثًا وسريعًا ومحسنًا لمحركات البحث المحلية. تتضمن الاستضافة والنطاق للعام الأول، بالإضافة إلى تكامل مباشر مع واتساب.",
    evoDetailTitle: "الباقة الاحترافية",
    evoDetailDesc: "حلنا الأكثر شيوعًا، مصمم للشركات التي ترغب في أتمتة اكتساب العملاء. بالإضافة إلى جميع ميزات الباقة الأساسية، تتضمن روبوت دردشة يعمل بالذكاء الاصطناعي قادر على الإجابة على الأسئلة الشائعة 24/7 وجمع العملاء المحتملين.",
    infDetailTitle: "الباقة المخصصة (INFINITY)",
    infDetailDesc: "للشركات المهيكلة التي تحتاج إلى حلول مخصصة. تغطي هذه الباقة تطوير التجارة الإلكترونية المتقدمة، أو تكامل واجهات برمجة التطبيقات المخصصة، وتتضمن استشارات استراتيجية شهرية.",
    subDetailsTitle: "لماذا تختار الاشتراك؟",
    subDetailsSubtitle: "العالم الرقمي يتطور بسرعة. تضمن اشتراكاتنا بقاء عملك دائمًا متقدمًا بخطوة.",
    maintDetailTitle: "الصيانة والدعم",
    maintDetailDesc: "راحة البال بوجود فريق فني متاح دائمًا. نحن نهتم بالتحديثات الأمنية، والنسخ الاحتياطي الأسبوعي، وإجراء تعديلات طفيفة على الموقع.",
    growthDetailTitle: "النمو والتسويق",
    growthDetailDesc: "المحرك لتوسيع نطاق عملك. ندير بنشاط حملاتك الإعلانية لتحقيق أقصى عائد على الاستثمار، ونوفر استشارات متخصصة.",
    a11yTitle: "إمكانية الوصول",
    a11yOversizedWidget: "أداة كبيرة جداً",
    a11yHighContrast: "تباين +",
    a11yHighlightLinks: "تمييز الروابط",
    a11yLargeText: "نص كبير",
    a11yTextSpacing: "تباعد النص",
    a11yStopAnimations: "إيقاف الرسوم المتحركة",
    a11yHideImages: "إخفاء الصور",
    a11yDyslexiaFriendly: "صديق لعسر القراءة",
    a11yBigCursor: "مؤشر كبير",
    a11yTooltips: "ملاحظات توضيحية",
    a11yLineHeight: "ارتفاع السطر",
    a11yTextAlign: "محاذاة النص",
    a11ySaturation: "تناغم الألوان",
    a11yResetAll: "إعادة ضبط جميع الإعدادات",
    a11yMoveHide: "نقل/إخفاء الأداة",
    a11yPositionLeft: "يسار",
    a11yPositionRight: "يمين",
    a11yPositionHide: "إخفاء",
    contactWhatsAppSub: "الرد في أقل من ساعتين",
    backButton: "العودة",
    promoTitle: "احصل على خصم 30%!",
    promoDesc: "اترك بريدك الإلكتروني لتلقي رمز خصم حصري لمشروعك الأول.",
    promoInput: "بريدك الإلكتروني",
    promoBtn: "الحصول على الخصم",
    promoSuccess: "تم إرسال الخصم! تحقق من بريدك الإلكتروني.",
    pricingHeroBadge: "السيادة الرقمية",
    pricingHeroTitle1: "اختر مستوى ",
    pricingHeroTitle2: "حريتك",
    pricingHeroDesc: "لا اشتراكات مزعجة. أنت تملك نظامك. استضافة في أوروبا. مدى الحياة.",
    pricingCtaEssential: "اختيار الأساسي",
    pricingCtaProfessional: "اختيار الاحترافي",
    pricingCtaCustom: "تحدث مع الإدارة",
    pricingDescEssential: "حضور رقمي مستقل",
    pricingDescProfessional: "أول موظف رقمي لك",
    pricingDescCustom: "نظام التشغيل الخاص بعملك",
    compTitle1: "مقارنة ",
    compTitle2: "تفصيلية",
    compFeature: "الميزة",
    oneShotTitle1: "خيارات ",
    oneShotTitle2: "لمرة واحدة",
    oneShotOption: "الخيار",
    careTitle1: "رعاية ",
    careTitle2: "Sogni",
    careTitle3: " (صيانة)",
    careDesc: "لأن الأنظمة المستقلة تحتاج أيضًا إلى صيانة",
    trust1Value: "100%",
    trust1Desc: "بيانات مستضافة في أوروبا",
    trust2Value: "0€",
    trust2Desc: "اشتراك SaaS شهري مزعج",
    trust3Value: "7-14d",
    trust3Desc: "وقت تسليم مضمون",
    finalCtaTitle: "غير متأكد من اختيارك؟",
    finalCtaDesc: "احجز تشخيصًا مجانيًا لمدة 20 دقيقة. سنقوم بتحليل وضعك الحالي ونخبرك بما تحتاجه بالضبط.",
    finalCtaBtn: "احجز تشخيصي المجاني",
    finalCtaSub: "بدون التزام. في تورينو أو عبر مكالمة فيديو.",
    faqTitle1: "الأسئلة ",
    faqTitle2: "الشائعة",
    viewComparison: "عرض المقارنة",
    hideComparison: "إخفاء المقارنة",
    addMaintenance: "إضافة صيانة سنوية",
    oneShotSectionTitle: "تحسين رؤية عملك",
    oneShotSectionDesc: "خدمات لمرة واحدة لإعطاء عملك دفعة فورية.",
    careDescExtended: "راحة البال بوجود فريق فني متاح دائمًا. نهتم بالتحديثات الأمنية والنسخ الاحتياطي والتعديلات الطفيفة للحفاظ على نظامك في أفضل حالاته."
  },
`;

  const newContent = content.substring(0, arStartIdx) + arabicTranslations + content.substring(frStartIdx);
  fs.writeFileSync('src/lib/translations.ts', newContent);
  console.log('Translations updated.');
} else {
  console.log('Could not find AR or FR block');
}
